// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdNYydMwoUtSoSgZA9YniGqclxWC-5Lik',
    appId: '1:87451670799:android:ba454b2751fd7d1a92467a',
    messagingSenderId: '87451670799',
    projectId: 'travelapp-c0f16',
    storageBucket: 'travelapp-c0f16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHakOkjkpazVQfgM9j24eU9pmbfkJeiYY',
    appId: '1:87451670799:ios:7597c8f146493b6592467a',
    messagingSenderId: '87451670799',
    projectId: 'travelapp-c0f16',
    storageBucket: 'travelapp-c0f16.firebasestorage.app',
    androidClientId: '87451670799-g4fhkq20e3vijhjljgmftheskmipdlmb.apps.googleusercontent.com',
    iosClientId: '87451670799-iuvuam4fh29580dbs0s44rso94c0i9m9.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3jeEWnJ0g4XdeybyjmtPD6yC4UJTnFAA',
    appId: '1:87451670799:web:28fc8b03e6524fd592467a',
    messagingSenderId: '87451670799',
    projectId: 'travelapp-c0f16',
    authDomain: 'travelapp-c0f16.firebaseapp.com',
    storageBucket: 'travelapp-c0f16.firebasestorage.app',
    measurementId: 'G-WGYPW3P7F8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHakOkjkpazVQfgM9j24eU9pmbfkJeiYY',
    appId: '1:87451670799:ios:7597c8f146493b6592467a',
    messagingSenderId: '87451670799',
    projectId: 'travelapp-c0f16',
    storageBucket: 'travelapp-c0f16.firebasestorage.app',
    androidClientId: '87451670799-g4fhkq20e3vijhjljgmftheskmipdlmb.apps.googleusercontent.com',
    iosClientId: '87451670799-iuvuam4fh29580dbs0s44rso94c0i9m9.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelApp',
  );

}